### ISSUE TITLE
wow! now I to can have an insane 11cps ca on Crystallpvp.cc! Thankyou Techale, very cool.

### ISSUE THREAD

**Issue by ErrorC0de5** [TechAle/gsplusplus#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by naygigga** [comment]
no only my config did that and my config is private

**Comment by SoggyBacco** [comment]
good luck with cfging the ca 👍

**Comment by naygigga** [comment]
240*

**Comment by arjunnain17** [comment]
if you have trouble cfging the ca then you probably shouldn't use it
