### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by linustouchtips** [TechAle/gsplusplus#62]
MM+3 pasted from my Momentum Shaders ...

**Comment by Wolfsurge** [comment]
he already credited you, look in the readme

**Comment by TechAle** [comment]
LMAO so, you are saying that vaimok talked so trash of us while mm3 literelly skidded the shader from someone else?
That's funny

**Comment by TechAle** [comment]
Imma fix this rn

**Comment by ZenovJB** [comment]
> LMAO so, you are saying that vaimok talked so trash of us while mm3 literelly skidded the shader from someone else?
> That's funny

dude they skidded trollgods ca and surround ofc their shaderchams r pasted
