### ISSUE TITLE
[BUG] wrong credits

### ISSUE THREAD

**Issue by cattyngmd** [TechAle/gsplusplus#67]
![image](https://user-images.githubusercontent.com/60744119/147417647-0e3f03e1-9f98-433b-a236-e9519436ef18.png)
pasted from moneymod

wheres my credits?????????

**Comment by TechAle** [comment]
Come on, be serious

**Comment by cattyngmd** [comment]
????

**Comment by ZenovJB** [comment]
hilarious bro keep it up

**Comment by cattyngmd** [comment]
![image](https://user-images.githubusercontent.com/60744119/147420242-00f01bd6-a4b8-4f6c-8db2-cc58ac854bac.png)

**Comment by TechAle** [comment]
Look at the git history lmao, you can see that i added bowbomb on the 8 of october, the same day BowMcBomb was released.
Now, stop baiting because i'm kinda tired, thanks

**Comment by Doogie13** [comment]
> ![image](https://user-images.githubusercontent.com/60744119/147420242-00f01bd6-a4b8-4f6c-8db2-cc58ac854bac.png)
This was for a skid sable wanted to use with gs++ lmao

**Comment by TechAle** [comment]
Yeha sable asked me 1000 times for a skid of mm3 + k5 + w+3 + gs++

**Comment by Skitttyy** [comment]
random dog LOL who even are you @TechAle
